apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: react-app
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`brunokrams.de`)
      kind: Rule
      services:
        - name: react-app
          port: 80
